site_name: A contactless, video-based baby monitor
site_url: https://Qicoco97.github.io/UofG-RTEP-BabyMonitor/
repo_url: https://github.com/Qicoco97/UofG-RTEP-BabyMonitor
nav:
  - Home: 'index.md'
  - Software Setup Instructions: 'setup/sw-setup.md'
  - Hardware Setup Instructions: 'setup/hw-setup.md'
  - Software Configuration Parameters: 'setup/config.md'
  - Troubleshooting: 'setup/troubleshooting.md'
theme: readthedocs
plugin:
  - mermaid2